name = "fish-bowl"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c25aea4da6fb5b366de061885558bd1a6b7b635d91f3c218c85e8ed8d8372c24"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
