name = "Fish Bowl Packwiz"
author = "Parker"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ba6da8c6f227dfbdc8e5f2abbe7fe2c975d78adb00b0cbc76453f7021623d06"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
