name = "Fish Bowl Packwiz"
author = "Parker"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b6f3a0ac68502c4910f4571f85fdbda75b370a6b2bf9e19a1005aac11b09d02"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
