name: Make Release Upon Tag
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Export mrpack
        run: packwiz modrinth export -o "FishBowl-${{ github.ref_name }}.mrpack"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: FishBowl-${{ github.ref_name }}.mrpack
