name: Make Release Upon Tag
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install packwiz
        run: |
          curl -L "https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip" -o packwiz.zip
          unzip packwiz.zip
          chmod +x packwiz
          sudo mv packwiz /usr/local/bin/packwiz

      - name: Export mrpack
        run: packwiz modrinth export -o FishBowl-${{ github.ref_name }}.mrpack

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: FishBowl-${{ github.ref_name }}.mrpack
